BASE_URL = 'https://qa-scooter.praktikum-services.ru'
CREATE_COURIER = '/api/v1/courier'
DELETE_COURIER = '/api/v1/courier'
LOGIN_COURIER = '/api/v1/courier/login'
CREATE_ORDER = '/api/v1/orders'
ORDER_LIST = '/api/v1/orders'
ACCEPT_ORDER = '/api/v1/orders/accept'
GET_ORDER_BY_ID = '/api/v1/orders/track'
FINISH_ORDER = '/api/v1/orders/finish'
CANCEL_ORDER = '/api/v1/orders/cancel'
COUNT_ORDERS = '/api/v1/courier'

TEXT_NOT_ENOUGH_CREDENTIALS_SIGN_IN_400 = "Недостаточно данных для входа"
TEXT_ORDER_NOT_FOUND_404 = "Заказ не найден"
TEXT_ACCOUNT_NOT_FOUND_404 = "Учетная запись не найдена"
TEXT_LOGIN_EXISTS_409 = "Этот логин уже используется. Попробуйте другой."
TEXT_NOT_ENOUGH_CREDENTIALS_SIGN_UP_400 = "Недостаточно данных для создания учетной записи"
TEXT_COURIER_WITH_ID_NOT_FOUND_404 = "Курьера с таким id не существует"
TEXT_ORDER_WITH_ID_NOT_FOUND_404 = "Заказа с таким id не существует"
TEXT_NOT_ENOUGH_CREDENTIALS_FIND_400 = "Недостаточно данных для поиска"
TEXT_PROCESSED_ORDER_409 = "Этот заказ уже в работе"
TEXT_NO_COURIER_WITH_ID_404 = "Курьера с таким id нет."
